### ISSUE TITLE
Kafka agent cannot link the producer and consumer trace when use auto-instrumentation java agent.

### ISSUE THREAD

**Issue by sweetxiaodai** [ppatierno/kafka-opentelemetry#10]
Please see the issue in attached image.
![Screenshot 2022-09-25 at 14 58 51](https://user-images.githubusercontent.com/90817719/192132111-63df3c5d-02fb-40c7-9291-f5499964abd2.png)
I will also attach my consumer code here. Just copy from spring apache kafka exmaples.

```
@SpringBootApplication
public class ConsumerApplication {

	public static void main(String[] args) {
		SpringApplication.run(ConsumerApplication.class, args);
	}
	@Bean
	public NewTopic topic() {
		return TopicBuilder.name("topic1")
				.partitions(10)
				.replicas(1)
				.build();
	}

	@KafkaListener(id = "myId", topics = "topic1")
	public void listen(String in) {
		System.out.println(in);
	}
}
```

**Comment by ppatierno** [comment]
I would close this issue and continue the discussion on https://github.com/open-telemetry/opentelemetry.io/issues/1781
